@startuml Code Sensor Update
== Просмотр карточки датчика ==

Пользователь -> Frontend: Просмотр детальной страницы датчика
Frontend -> Frontend: Проверка актуальности токенов

alt Срок годности Refresh-токена истек
    Frontend -x Пользователь: разлогировать пользователя, переадресовать на /login
else Срок годности Access-токена истек
    Frontend -> BFF: запросить новый Access-токен
    return передать новый Access-токен
end

Frontend -> BFF: запрос информации о датчике
BFF -> BFF: идентификация, аутентификация, авторизация, аккаунтинг
BFF -> СУБД: запрос информации о пользователе и правах
activate СУБД
return ответ на SQL запрос
deactivate СУБД

alt Доступ запрещен
    BFF -> Frontend: вернуть ответ 403
    Frontend -x Пользователь: отобразить ошибку
end

BFF -> СУБД: получить информацию о датчике
activate СУБД
return ответ на SQL запрос
deactivate СУБД
BFF -> Frontend: венруть информацию о датчике
Frontend -x Пользователь: отобразить датчик и его информацию


== Внесение изменений в датчик ==

Пользователь -> Frontend: вносит изменения в состояние датчика и сохраняет
Frontend -> Frontend: Проверка актуальности токенов...
Frontend -> Frontend: Нарисовать загрузку
Frontend -> BFF: Запрос на изменение состояния датчика
BFF -> BFF: идентификация, аутентификация, авторизация, аккаунтинг...

BFF -> Redis: создать сообщение "Запрос на изменение состояния датчика"
activate Redis
BFF -> Frontend: ответить на HTTP запрос с идентификатором созданного сообщения
Frontend -> Frontend: начать периодический опрос о состоянии сообщения "Запрос на изменение состояния датчика"
activate Frontend
Redis -> SensorAgent: передать сообщение "Запрос на изменение состояния датчика"
deactivate Redis

alt Отсутствует WebSocket-соединение с датчиком
    SensorAgent -x Redis: отложить сообщение "Запрос на изменение состояния датчика" в конец очереди
end

SensorAgent -> Датчик: изменить состояние датчика по WebSocket
activate Датчик
return новое состояние датчика
deactivate Датчик

SensorAgent -> Redis: создать сообщение "Изменение состояния датчика по запросу"
activate Redis
Redis -> BFF: передать сообщение "Изменение состояния датчика по запросу"
deactivate Redis
BFF -> СУБД: записать новое состояние датчика
activate СУБД
СУБД -x BFF: ответ на SQL запрос
deactivate СУБД

Frontend -> BFF: запрос результата обновления датчика
return новое состояние датчика
deactivate Frontend

Frontend -x Пользователь: отображение датчика и его информацию (обновленную)
@enduml