[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "temperature-api"
version = "0.1.0"
requires-python = ">=3.13"
dependencies = ["fastapi", "uvicorn"]

[tool.setuptools.packages.find]
include = ["temperature_api*"]
exclude = ["tmp*"]


[tool.setuptools.package-data]
"*" = ["*.html", "*.css", "*.js", "*.svg", "*.ico", "*.mo"]
