# Generated by Django 5.2.4 on 2025-07-07 17:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bff', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='device_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bff.devicetype'),
        ),
        migrations.AlterField(
            model_name='devicestateledger',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='state', to='bff.device'),
        ),
        migrations.AlterField(
            model_name='devicestateproperty',
            name='device_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bff.devicetype'),
        ),
    ]
